window.SITE_DATA = {
  "navGallery": "Gallery",
  "navHowItWorks": "How It Works",
  "navWhyUs": "Why Us",
  "navPackages": "Packages",
  "navCta": "Get Started",
  "logoTextMain": "Northshore",
  "logoTextAccent": "Gardens",
  "logoTextStudio": "Studio",
  "footerTagline": "Landscape Design - Northbrook, Illinois",
  "heroEyebrow": "Thinking about your yard?",
  "heroTitle": "A better yard starts with a few photos.",
  "heroSubtext": "Answer a couple quick questions about what you're thinking. We'll get a feel for your space and share initial ideas with clear direction.",
  "heroPrimaryCta": "Free Consult",
  "heroSecondaryCta": "View Examples",
  "heroCtaMicrocopy": "Free to start. Professional plans available if you want to continue.",
  "heroPoint1": "Flat-fee design",
  "heroPoint2": "Locally based",
  "heroPoint3": "<7days delivery",
  "galleryEyebrow": "Proof",
  "galleryTitle": "Elevated curb appeal.",
  "galleryIntro": "Small, intentional changes can transform how your home feels.",
  "howItWorksEyebrow": "How It Works",
  "howItWorksTitle": "Simple from start to finish.",
  "howItWorksIntro": "You work directly with a designer from the start, keeping the process personal and low-pressure.",
  "step1Title": "Share a few details about your yard",
  "step1Body": "Answer a couple questions and upload photos of your yard.",
  "step2Title": "Hear back from a designer",
  "step2Body": "We review your space and reach out with ideas tailored to your yard.",
  "step3Title": "Move forward if it feels right",
  "step3Body": "If you choose to continue, you can purchase a professional plan. If not, you still leave with ideas.",
  "whyEyebrow": "Why This Is Different",
  "whyTitle": "Focused on Design",
  "whyBody": "Traditional landscaping is driven by installation incentives. We take a different approach. Based in Northbrook, IL, we create tailored yard plans with no inflated scope. A refined design service you can hand off to a contractor or build yourself, with complimentary coordination if requested.",
  "diff1Title": "Design-first approach",
  "diff1Body": "No installation incentives. Just a complete plan aligned with your vision and budget.",
  "diff2Title": "Flat-fee and simple",
  "diff2Body": "Clear pricing with no price creep and no pressure to expand.",
  "diff3Title": "Local to the Northshore",
  "diff3Body": "Designed around Midwestern conditions and plants available at local nurseries.",
  "diff4Title": "Personal touch",
  "diff4Body": "Work directly with a designer who responds with ideas tailored to your yard.",
  "diff5Title": "Fast turnaround",
  "diff5Body": "Receive a detailed professional plan in under 7 days.",
  "packagesEyebrow": "Packages",
  "packagesTitle": "Every design is created by a local expert. No templates or algorithms.",
  "packagesIntro": "Start with a quick consultation. Choose a plan when you're ready to move forward.",
  "package1Label": "Most homeowners choose this",
  "package1Title": "Signature Plan",
  "package1Subtitle": "A complete, build-ready design for your yard.",
  "package1Item1": "Custom design tailored to your home",
  "package1Item2": "Top-view layout with plant names",
  "package1Item3": "Plant quantities and specifications",
  "package1Item4": "Plant sheet with bloom season, color palette, and sun info",
  "package1Item5": "Delivered within 7 days",
  "package1Item6": "Optional: coordination with a trusted contractor",
  "package1Note": "Everything you need to move forward with clarity, whether you're working with a contractor or building it yourself.",
  "package2Label": "For more guidance",
  "package2Title": "Premium Plan",
  "package2Subtitle": "Everything in Signature, with added clarity and flexibility.",
  "package2Item1": "Everything in Signature Plan",
  "package2Item2": "1 revision",
  "package2Item3": "Plant substitutions",
  "package2Item4": "Installation guidelines",
  "package2Item5": "Phasing suggestions",
  "package2Item6": "Nursery budget sheet",
  "package2Note": "Best if you want more flexibility or plan to build in stages.",
  "contactTitle": "Tell us what you're thinking about for your yard.",
  "contactIntro": "Send a description or photos of your space. Our designers will take a look and reach out with thoughtful suggestions.",
  "contactMessageLabel": "Message",
  "contactEmailLabel": "Email",
  "contactAttachmentLabel": "Add a photo (optional)",
  "contactSubmitButton": "Send Message",
  "contactSuccessTitle": "Thank you! We'll get back to you as soon as possible.",
  "contactSuccessBody": "Photos help us give more specific ideas. Feel free to send more details anytime."
};
