window.SITE_DATA = {
  "navGallery": "Gallery",
  "navHowItWorks": "How It Works",
  "navWhyUs": "Why Us",
  "navPackages": "Packages",
  "navCta": "Get Started",
  "logoTextMain": "Northshore",
  "logoTextAccent": "Gardens",
  "logoTextStudio": "Studio",
  "heroEyebrow": "Front yard design for North Shore homes",
  "heroTitle": "A better front yard starts with a few photos.",
  "heroSubtext": "Send a few yard photos and answer a couple quick questions. We'll personally review your space and respond with thoughtful design ideas before you decide whether to move forward.",
  "heroPrimaryCta": "Get Quick Ideas",
  "heroSecondaryCta": "View Examples",
  "heroPoint1": "Low pressure",
  "heroPoint2": "No meetings required",
  "heroPoint3": "Zone 5b aware",
  "proofLabelLeft": "Curated proof",
  "proofLabelRight": "Before -> After",
  "beforeCaption": "Before",
  "afterCaption": "After",
  "proofNote": "Thoughtful layouts, cleaner structure, and planting direction tailored to the house instead of generic templates.",
  "galleryEyebrow": "Proof",
  "galleryTitle": "Curated transformations that build trust fast.",
  "galleryIntro": "A few stronger examples do more than a crowded gallery. These are here to show range, restraint, and the kind of clarity homeowners are actually looking for.",
  "galleryCard1Title": "Stronger structure without feeling overdone",
  "galleryCard1Body": "Used as a trust-builder near the top of the page, not buried in a separate gallery-first experience.",
  "galleryCard2Title": "Refined curb appeal from photos and context",
  "galleryCard2Body": "Enough visual proof to feel credible, without overwhelming the homepage with every project at once.",
  "galleryCard3Title": "Curated, calm, and easy to trust",
  "galleryCard3Body": "The homepage proves capability first, then invites the user into a simple intake instead of pushing straight to checkout.",
  "howItWorksEyebrow": "How It Works",
  "howItWorksTitle": "Simple enough to start in minutes.",
  "step1Title": "Send photos + answer a few questions",
  "step1Body": "A short, conversational intake helps you share just enough context without getting pulled into a long form.",
  "step2Title": "Receive thoughtful ideas personally",
  "step2Body": "You hear from a real designer, not an automated checkout sequence. The first interaction feels helpful, not transactional.",
  "step3Title": "Choose a package if you want to move forward",
  "step3Body": "Packages still exist, but they are no longer the forced first action. The relationship starts with trust.",
  "whyEyebrow": "Why This Is Different",
  "whyTitle": "A refined online design product, not a contractor funnel.",
  "whyBody": "The experience is designed to feel calm, thoughtful, and low-pressure from the first click. Homeowners get useful direction first. Packages come later.",
  "diff1Title": "No contractor upsells",
  "diff1Body": "Use your own installer, nursery, or timeline.",
  "diff2Title": "No pressure",
  "diff2Body": "The initial step is simply to get thoughtful ideas.",
  "diff3Title": "No meetings required",
  "diff3Body": "The flow is built around photos and a short intake.",
  "diff4Title": "Flat-fee design",
  "diff4Body": "Clear productized service once they choose to continue.",
  "diff5Title": "North Shore / Zone 5b expertise",
  "diff5Body": "Local conditions and neighborhood fit are part of the value.",
  "packagesEyebrow": "Packages",
  "packagesTitle": "Still available. Just no longer the first forced step.",
  "packagesIntro": "Once a homeowner has seen your style and heard from you personally, these become the natural next step instead of the entry point.",
  "package1Label": "Signature Plan",
  "package1Badge": "Most straightforward",
  "package1Title": "Fast, polished design direction.",
  "package1Item1": "Before / after design direction",
  "package1Item2": "Plan view and plant names",
  "package1Item3": "Plant sheet and quantities",
  "package1Item4": "Delivered within 7 days",
  "package1Item5": "No revision",
  "package1Note": "Available after your initial ideas.",
  "package2Label": "Premium Plan",
  "package2Badge": "For more guidance",
  "package2Title": "Everything in the Signature Plan, plus clearer execution help.",
  "package2Item1": "1 revision included",
  "package2Item2": "Plant spacing and sizing guidance",
  "package2Item3": "Substitution options",
  "package2Item4": "Installation steps and phasing direction",
  "package2Item5": "More contractor-ready detail",
  "package2Note": "Presented as the next step, not a paywall.",
  "finalCtaEyebrow": "Thinking about your yard?",
  "finalCtaTitle": "Send a photo and get a thoughtful first response.",
  "finalCtaBody": "A quick phone photo is enough to start. No sales pressure. No spam. Just a clearer sense of what your yard could become.",
  "finalCtaButton": "Get Quick Ideas",
  "finalCtaMicrocopy": "You review the ideas first. Purchase only if it feels right.",
  "footerTagline": "Landscape Design - Northbrook, Illinois",
  "contactEyebrow": "Contact Us",
  "contactTitle": "Tell us what you are thinking about.",
  "contactIntro": "Share your questions, project goals, and any helpful photos. We usually reply within one business day.",
  "contactNameLabel": "Name",
  "contactEmailLabel": "Email",
  "contactMessageLabel": "Message",
  "contactAttachmentLabel": "Attachments (optional)",
  "contactAttachmentHint": "You can attach up to 5 images.",
  "contactSubmitButton": "Send Message",
  "contactSuccessTitle": "Thanks, your message was sent.",
  "contactSuccessBody": "We received your message and will follow up shortly."
};
